### ISSUE TITLE
Null locale parameters on Samsung 4.x devices

### ISSUE THREAD

**Issue by KarsonKimbrel** [mta452/Tehreer-Android#8]
For whatever reason Samsung devices are crashing in some cases (Android 4.x only).

Fatal Exception: java.lang.NullPointerException
       at java.util.Locale.<init>(Locale.java:273)
       at com.mta.tehreer.sfnt.tables.NameTable$Record.locale(NameTable.java:165)
       at com.mta.tehreer.graphics.TypefaceDescription.getEnglishName(TypefaceDescription.java:65)
       at com.mta.tehreer.graphics.TypefaceDescription.getFamilyName(TypefaceDescription.java:97)
       at com.mta.tehreer.graphics.TypefaceDescription.deduce(TypefaceDescription.java:143)
       at com.mta.tehreer.graphics.Typeface.init(Typeface.java:133)
       at com.mta.tehreer.graphics.Typeface.<init>(Typeface.java:84)
       ...

**Comment by KarsonKimbrel** [comment]
Closed as it looks like it has been fixed in 2.1, was using 2.0.
